spring:
  application:
    name: discovery-server

server:
  port: 8761

eureka:
  instance:
    preferIpAddress: false
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/