spring:
  application:
    name: collector
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server

eureka:
  instance:
    preferIpAddress: false
    hostname: COLLECTOR
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/